name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Run action against test file
        id: read
        uses: ./
        with:
          path: package.json
          trim: true

      - name: Print action version from output
        run: echo "Version -> ${{ fromJson(steps.read.outputs.content).version }}"
